config/routes.rb
Slyde::Application.routes.draw do
  resources :decks
  get "home/index"
  
  resources :users do
      resources :decks
  end

   root :to => "home#index"

end

app/models/deck.rb
class Deck < ActiveRecord::Base

  belongs_to :user

# Paperclip
  has_attached_file :doc,
					:url => "/in/:id/:basename.:extension",
					:path => ":rails_root/public/in/:id/:basename.:extension"

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :decks

# Paperclip
#  has_attached_file :doc,
#					:url => "/in/:id/:basename.:extension",
#					:path => ":rails_root/public/in/:id/:basename.:extension"
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  # GET /decks
  # GET /decks.xml
  def index
    @decks = Deck.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.xml
  def show
    @deck = Deck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deck }
    end
  end

  # GET /decks/new
  # GET /decks/new.xml
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:user_id])
  end

  # POST /decks
  # POST /decks.xml
  def create
  	#paperclip says to use the below:
    #@deck = Deck.create(params[:deck])
	
	@user = User.find(params[:id])
	@deck = @user.decks.create( params[:deck] )
	redirect_to user_path(@user)
	
    #@deck = Deck.new(params[:deck])

    respond_to do |format|
      if @deck.save
        format.html { redirect_to(@deck, :notice => 'Deck was successfully created.') }
        format.xml  { render :xml => @deck, :status => :created, :location => @deck }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @deck.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.xml
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to(@deck, :notice => 'Deck was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deck.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.xml
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to(decks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
  
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<% form_for :deck, @deck, :url => decks_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
  <%= submit_tag value="Submit" %>
<% end %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>
<%= link_to 'Home', root_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @decks.each do |deck| %>
  <tr>
    <td><%= link_to 'Show', deck %></td>
    <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
    <td><%= link_to 'Destroy', deck, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deck', new_deck_path %>
<%= link_to 'Home', root_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>
<% form_for :deck, @deck, :url => decks_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
  <%= submit_tag value="Submit" %>
<% end %>

<%= link_to 'Back', decks_path %>
<%= link_to 'Home', root_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @user.doc.url %>

<%= Deck.connection.select_all("select * from decks") %>
<br><br>
<%= Deck.find(params[:id]) %>
<br><br>
<%= @deck.doc.name %>
<%= @deck.doc.whiny %>


<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>
<%= link_to 'Home', root_path %>

app/views/home/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Slyde It</h1> 
<h2>Test Application</h2>
Goal for this page: 
<br>
To let the user create a new account and upload a file (Success! 7/3)
<br>
To have a model that has users able to have multiple files (Done 7/8)
<br>
Easily upload a file, know its relation to user
<br>
To save a reference to the file, for one-click access
<br>
To create a randomized refrence to that one-click, and make it sharable
<br>
decouple from my computer

<br>
<br>
<br>
<br>

<%#= render 'form' %>

<% form_for :user, @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
  <%= submit_tag value="Submit" %>
<% end %>

<br>
<br>
<%= link_to 'Users', users_path %>
<%= link_to 'Decks', decks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slyde</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<% form_for :user, @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
  <%= submit_tag value="Submit" 
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
	<td> User <%= user.id %> <%#=User.find(params[user.id])%></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>


<%= link_to 'Back', users_path %>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>





<%= User.connection.select_all("select * from users") %>
<br><br>
<%= User.find(params[:id]) %>
<br><br>

<h2>Attach Deck to this User with Paperclip</h2>
<% form_for :deck, @deck, :url => decks_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
  <%= submit_tag value="Submit" %>
<% end %>

<br><br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Home', root_path %>